name: emtalik
description: Senior Project built with flutter
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  motion_toast: ^2.1.5
  localization: ^2.1.0
  provider: ^6.0.2
  http: ^0.13.4
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Changa
      fonts:
        - asset: fonts/Changa-Light.ttf
          weight: 300
        - asset: fonts/Changa-Medium.ttf
          weight: 500
        - asset: fonts/Changa-Bold.ttf
          weight: 700
        - asset: fonts/Changa-ExtraBold.ttf
          weight: 800

  assets:
    - lib/i18n/


      

      
  
